"""
Ryle Pipeline — Seed Data Part 2 (Meses 8-13, Semanas 27-52)
Importado e concatenado pelo seed_data.py principal.
"""

# Meses 8-13 (Semanas 27-52)
PLANO_ANUAL_PART2: list[tuple[int, int, str, int, str, str, str, str]] = [
    # MÊS 8 — A Oração e a Comunhão com Deus (Sem 27-30)
    (27,1,"Sáb",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","Filipenses 4.6-7","Não andeis ansiosos — a paz que excede todo entendimento"),
    (27,2,"Dom",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","Hebreus 4.14-16","Acheguemo-nos com confiança ao trono da graça"),
    (27,3,"Seg",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","1 João 5.14-15","Se pedirmos segundo a Sua vontade, Ele nos ouve"),
    (27,4,"Ter",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","Mateus 7.7-11","Pedi e dar-se-vos-á; buscai e achareis"),
    (27,5,"Qua",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","Tiago 5.13-16","A oração fervorosa do justo pode muito"),
    (27,6,"Qui",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","Salmo 62.5-8","Confiai nEle em todo tempo; derramai o coração"),
    (27,7,"Sex",8,"A Oração e a Comunhão com Deus","O Privilégio da Oração","Jeremias 33.3","Clama a mim, e responder-te-ei coisas grandes"),
    (28,1,"Sáb",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Mateus 6.5-8","Como não orar — a hipocrisia e a vã repetição"),
    (28,2,"Dom",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Mateus 6.9-13","Pai nosso que estás nos céus — o modelo completo"),
    (28,3,"Seg",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Lucas 11.5-10","A parábola do amigo importuno — persistência"),
    (28,4,"Ter",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Lucas 18.1-8","A viúva e o juiz iníquo — orar sem esmorecer"),
    (28,5,"Qua",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Salmo 5.1-3","De manhã ouves a minha voz"),
    (28,6,"Qui",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Daniel 6.10-13","Daniel orava três vezes ao dia"),
    (28,7,"Sex",8,"A Oração e a Comunhão com Deus","O Pai-Nosso: O Modelo de Jesus","Marcos 1.35-38","Jesus se levantou de madrugada e foi orar"),
    (29,1,"Sáb",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","João 4.21-24","Os verdadeiros adoradores adorarão em espírito e em verdade"),
    (29,2,"Dom",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","Salmo 95.1-7","Vinde, adoremos e prostremo-nos"),
    (29,3,"Seg",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","Romanos 12.1-2","Apresentai os vossos corpos em sacrifício vivo"),
    (29,4,"Ter",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","Salmo 100.1-5","Entrai pelas portas dele com ações de graça"),
    (29,5,"Qua",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","Hebreus 12.28-29","O nosso Deus é fogo consumidor"),
    (29,6,"Qui",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","Salmo 84.1-4","Quão amáveis são os Teus tabernáculos!"),
    (29,7,"Sex",8,"A Oração e a Comunhão com Deus","A Adoração Verdadeira","Apocalipse 5.11-14","Digno é o Cordeiro — adoração cósmica"),
    (30,1,"Sáb",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Salmo 119.97-104","Oh! Quanto amo a Tua lei!"),
    (30,2,"Dom",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Josué 1.7-9","Medita na lei de dia e de noite"),
    (30,3,"Seg",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Salmo 1.1-6","Bem-aventurado o que medita na lei — árvore plantada"),
    (30,4,"Ter",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Salmo 119.9-16","De que maneira poderá o jovem guardar puro o seu caminho?"),
    (30,5,"Qua",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Salmo 19.7-11","A lei do Senhor é perfeita e restaura a alma"),
    (30,6,"Qui",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Isaías 55.10-11","A Palavra não voltará vazia"),
    (30,7,"Sex",8,"A Oração e a Comunhão com Deus","A Meditação na Palavra","Hebreus 4.12-13","A Palavra de Deus é viva e eficaz"),
    # MÊS 9 — A Palavra de Deus e a Igreja (Sem 31-34)
    (31,1,"Sáb",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","2 Timóteo 3.14-17","Toda Escritura é inspirada por Deus"),
    (31,2,"Dom",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","2 Pedro 1.19-21","Homens santos falaram movidos pelo Espírito"),
    (31,3,"Seg",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","Salmo 119.89-91","A Tua palavra está firmada nos céus"),
    (31,4,"Ter",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","Mateus 5.17-19","Nem um jota ou til jamais passará da Lei"),
    (31,5,"Qua",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","Isaías 40.6-8","A Palavra do nosso Deus permanece"),
    (31,6,"Qui",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","João 17.17","Santifica-os na verdade; a Tua palavra é a verdade"),
    (31,7,"Sex",9,"A Palavra de Deus e a Igreja","A Autoridade das Escrituras","Salmo 12.6-7","As palavras do Senhor são puras como prata refinada"),
    (32,1,"Sáb",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Salmo 119.105-112","Lâmpada para os meus pés é a Tua palavra"),
    (32,2,"Dom",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Provérbios 6.20-23","O mandamento é lâmpada, a instrução é luz"),
    (32,3,"Seg",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Salmo 119.129-136","A exposição das Tuas palavras dá luz"),
    (32,4,"Ter",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Salmo 119.49-56","A Tua palavra me vivificou na minha angústia"),
    (32,5,"Qua",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Deuteronômio 30.11-14","A Palavra está mui perto de ti"),
    (32,6,"Qui",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Mateus 4.4-7","Está escrito — Jesus vence a tentação com a Palavra"),
    (32,7,"Sex",9,"A Palavra de Deus e a Igreja","A Lâmpada para os Pés","Atos 17.10-12","Os bereanos examinavam as Escrituras diariamente"),
    (33,1,"Sáb",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","1 Coríntios 12.12-18","Um corpo, muitos membros"),
    (33,2,"Dom",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","Efésios 4.11-16","Até que cheguemos à unidade da fé"),
    (33,3,"Seg",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","Mateus 16.16-19","Sobre esta pedra edificarei a minha igreja"),
    (33,4,"Ter",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","Atos 2.42-47","Perseveravam na doutrina, comunhão, partir do pão"),
    (33,5,"Qua",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","1 Pedro 2.4-6","Pedras vivas edificadas como casa espiritual"),
    (33,6,"Qui",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","Hebreus 10.24-25","Não deixemos de congregar-nos"),
    (33,7,"Sex",9,"A Palavra de Deus e a Igreja","A Igreja como Corpo de Cristo","Colossenses 1.17-20","Ele é a cabeça do corpo, a igreja"),
    (34,1,"Sáb",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","Romanos 10.14-17","A fé vem pelo ouvir"),
    (34,2,"Dom",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","1 Coríntios 11.23-26","A Ceia do Senhor — fazei isto em memória de mim"),
    (34,3,"Seg",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","Mateus 28.18-20","Ide, fazei discípulos, batizando-os"),
    (34,4,"Ter",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","Atos 2.38-41","Arrependei-vos e cada um seja batizado"),
    (34,5,"Qua",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","1 Coríntios 10.16-17","O cálice da bênção e o pão que partimos"),
    (34,6,"Qui",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","Atos 6.2-4","A prioridade da pregação"),
    (34,7,"Sex",9,"A Palavra de Deus e a Igreja","Os Meios de Graça","Colossenses 3.16-17","A Palavra habite ricamente em vós"),
    # MÊS 10 — O Advento e a Encarnação (Sem 35-38)
    (35,1,"Sáb",10,"O Advento e a Encarnação","As Profecias Messiânicas","Gênesis 3.14-15","A semente da mulher — o protoevangelho"),
    (35,2,"Dom",10,"O Advento e a Encarnação","As Profecias Messiânicas","Isaías 7.14","A virgem conceberá — Emanuel"),
    (35,3,"Seg",10,"O Advento e a Encarnação","As Profecias Messiânicas","Miquéias 5.2-4","De Belém sairá o dominador"),
    (35,4,"Ter",10,"O Advento e a Encarnação","As Profecias Messiânicas","Isaías 9.2-7","Um menino nos nasceu — Maravilhoso Conselheiro"),
    (35,5,"Qua",10,"O Advento e a Encarnação","As Profecias Messiânicas","Isaías 11.1-5","O rebento do tronco de Jessé"),
    (35,6,"Qui",10,"O Advento e a Encarnação","As Profecias Messiânicas","Malaquias 3.1-3","O mensageiro que prepara o caminho"),
    (35,7,"Sex",10,"O Advento e a Encarnação","As Profecias Messiânicas","Zacarias 9.9-10","O Rei justo, humilde, montado sobre um jumento"),
    (36,1,"Sáb",10,"O Advento e a Encarnação","O Verbo se Fez Carne","João 1.1-5","No princípio era o Verbo"),
    (36,2,"Dom",10,"O Advento e a Encarnação","O Verbo se Fez Carne","João 1.10-14","O Verbo se fez carne e habitou entre nós"),
    (36,3,"Seg",10,"O Advento e a Encarnação","O Verbo se Fez Carne","Filipenses 2.5-11","Sendo em forma de Deus, esvaziou-se"),
    (36,4,"Ter",10,"O Advento e a Encarnação","O Verbo se Fez Carne","Hebreus 1.1-4","O Filho: resplendor da glória"),
    (36,5,"Qua",10,"O Advento e a Encarnação","O Verbo se Fez Carne","Colossenses 1.15-17","A imagem do Deus invisível"),
    (36,6,"Qui",10,"O Advento e a Encarnação","O Verbo se Fez Carne","Hebreus 2.14-18","Participou de carne e sangue"),
    (36,7,"Sex",10,"O Advento e a Encarnação","O Verbo se Fez Carne","1 Timóteo 3.16","Grande é o mistério da piedade"),
    (37,1,"Sáb",10,"O Advento e a Encarnação","O Nascimento do Salvador","Lucas 1.26-33","A anunciação a Maria"),
    (37,2,"Dom",10,"O Advento e a Encarnação","O Nascimento do Salvador","Lucas 2.1-7","O Rei dos reis nasce em manjedoura"),
    (37,3,"Seg",10,"O Advento e a Encarnação","O Nascimento do Salvador","Lucas 2.8-14","Glória a Deus nas maiores alturas"),
    (37,4,"Ter",10,"O Advento e a Encarnação","O Nascimento do Salvador","Mateus 1.20-23","'Chamarás o nome de Emanuel'"),
    (37,5,"Qua",10,"O Advento e a Encarnação","O Nascimento do Salvador","Lucas 2.25-32","Simeão: os meus olhos viram a Tua salvação"),
    (37,6,"Qui",10,"O Advento e a Encarnação","O Nascimento do Salvador","Mateus 2.1-6","Os magos do Oriente"),
    (37,7,"Sex",10,"O Advento e a Encarnação","O Nascimento do Salvador","Gálatas 4.4-7","Na plenitude do tempo, Deus enviou Seu Filho"),
    (38,1,"Sáb",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","Mateus 1.22-23","Emanuel — a promessa cumprida"),
    (38,2,"Dom",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","João 14.8-11","'Quem me vê a mim, vê o Pai'"),
    (38,3,"Seg",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","Hebreus 4.14-16","Sumo sacerdote que compadece"),
    (38,4,"Ter",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","Mateus 28.18-20","'Eis que estou convosco todos os dias'"),
    (38,5,"Qua",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","Apocalipse 21.3-5","'Eis o tabernáculo de Deus com os homens'"),
    (38,6,"Qui",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","Colossenses 2.9-10","Nele habita toda a plenitude da Divindade"),
    (38,7,"Sex",10,"O Advento e a Encarnação","Emanuel: Deus Conosco","Isaías 12.1-6","Grande é o Santo de Israel no meio de ti"),
    # MÊS 11 — A Soberania de Deus e a Providência (Sem 39-42)
    (39,1,"Sáb",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","Salmo 103.19-22","O seu reino domina tudo"),
    (39,2,"Dom",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","Isaías 46.9-11","O meu conselho permanecerá de pé"),
    (39,3,"Seg",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","Daniel 4.34-35","Ele age segundo a Sua vontade"),
    (39,4,"Ter",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","Salmo 115.1-3","O nosso Deus faz tudo o que Lhe apraz"),
    (39,5,"Qua",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","1 Crônicas 29.11-13","Tua é a grandeza, o poder, a glória"),
    (39,6,"Qui",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","Atos 17.24-28","NEle vivemos, nos movemos e existimos"),
    (39,7,"Sex",11,"A Soberania de Deus e a Providência","Deus Reina sobre Tudo","Apocalipse 19.6-8","'Aleluia! Pois reina o Senhor Todo-Poderoso'"),
    (40,1,"Sáb",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","Efésios 1.3-6","Nos elegeu antes da fundação do mundo"),
    (40,2,"Dom",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","Romanos 9.10-16","'Terei misericórdia de quem me aprouver'"),
    (40,3,"Seg",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","João 15.16-19","'Não fostes vós que me escolhestes'"),
    (40,4,"Ter",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","2 Tessalonicenses 2.13-14","Deus vos escolheu desde o princípio"),
    (40,5,"Qua",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","1 Pedro 2.9-10","Geração eleita, sacerdócio real"),
    (40,6,"Qui",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","Romanos 8.28-30","A cadeia de ouro: conhecidos, predestinados, chamados"),
    (40,7,"Sex",11,"A Soberania de Deus e a Providência","A Eleição Incondicional","João 6.37-40","'Todo aquele que o Pai me dá, esse virá a mim'"),
    (41,1,"Sáb",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Efésios 1.11-14","Faz tudo conforme o Seu conselho"),
    (41,2,"Dom",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Provérbios 19.21","O desígnio do Senhor permanecerá"),
    (41,3,"Seg",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Isaías 55.8-11","Os meus pensamentos não são os vossos"),
    (41,4,"Ter",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Romanos 11.33-36","Ó profundidade da riqueza e da sabedoria!"),
    (41,5,"Qua",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Jó 42.1-6","Agora os meus olhos Te veem"),
    (41,6,"Qui",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Salmo 33.10-12","O conselho do Senhor dura para sempre"),
    (41,7,"Sex",11,"A Soberania de Deus e a Providência","A Vontade Soberana de Deus","Atos 4.27-28","O que a Tua mão e propósito predeterminaram"),
    (42,1,"Sáb",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Gênesis 50.19-21","Deus o tornou em bem"),
    (42,2,"Dom",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Ester 4.13-16","'Para conjuntura como esta foste elevada'"),
    (42,3,"Seg",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Romanos 8.28","Todas as coisas cooperam para o bem"),
    (42,4,"Ter",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Provérbios 16.1-3","Do Senhor é a resposta da língua"),
    (42,5,"Qua",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Mateus 10.29-31","Nem um pardal cai sem o consentimento do Pai"),
    (42,6,"Qui",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Salmo 139.1-6","Tu me sondas e me conheces"),
    (42,7,"Sex",11,"A Soberania de Deus e a Providência","A Providência nos Detalhes","Jeremias 29.11-13","Eu é que sei os planos que tenho a vosso respeito"),
    # MÊS 12 — Guerra Espiritual e Vida de Fé (Sem 43-46)
    (43,1,"Sáb",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","1 Pedro 5.8-9","O diabo anda ao redor como leão rugindo"),
    (43,2,"Dom",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","2 Coríntios 11.13-15","Satanás se disfarça de anjo de luz"),
    (43,3,"Seg",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","Gênesis 3.1-6","A anatomia da tentação original"),
    (43,4,"Ter",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","2 Coríntios 2.10-11","Não ignorar suas ciladas"),
    (43,5,"Qua",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","João 8.44","O diabo é pai da mentira"),
    (43,6,"Qui",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","1 João 4.1-4","Maior é o que está em vós que o mundo"),
    (43,7,"Sex",12,"Guerra Espiritual e Vida de Fé","O Inimigo e Suas Estratégias","Lucas 4.1-8","A tentação de Jesus no deserto"),
    (44,1,"Sáb",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","Efésios 6.10-13","Revesti-vos de toda a armadura de Deus"),
    (44,2,"Dom",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","Efésios 6.14-17","Cinto, couraça, escudo, espada do Espírito"),
    (44,3,"Seg",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","Efésios 6.18-20","Orando em todo tempo no Espírito"),
    (44,4,"Ter",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","2 Coríntios 10.3-5","As armas da nossa milícia"),
    (44,5,"Qua",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","Romanos 13.12-14","Revistamo-nos das armas da luz"),
    (44,6,"Qui",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","1 Tessalonicenses 5.6-8","Sejamos sóbrios, com a couraça da fé"),
    (44,7,"Sex",12,"Guerra Espiritual e Vida de Fé","A Armadura Completa de Deus","Isaías 59.16-17","O braço do Senhor trouxe salvação"),
    (45,1,"Sáb",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","1 João 5.4-5","Esta é a vitória: a nossa fé"),
    (45,2,"Dom",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","Colossenses 2.13-15","Triunfou deles na cruz"),
    (45,3,"Seg",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","Romanos 8.31-34","Se Deus é por nós, quem será contra nós?"),
    (45,4,"Ter",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","1 Coríntios 15.55-58","Onde está, ó morte, o teu aguilhão?"),
    (45,5,"Qua",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","2 Coríntios 2.14","Sempre nos conduz em triunfo em Cristo"),
    (45,6,"Qui",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","Apocalipse 12.10-11","Venceram pelo sangue do Cordeiro"),
    (45,7,"Sex",12,"Guerra Espiritual e Vida de Fé","A Vitória em Cristo","João 16.33","Tende bom ânimo; eu venci o mundo"),
    (46,1,"Sáb",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Hebreus 11.1-6","A fé é a certeza — sem fé é impossível agradar"),
    (46,2,"Dom",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Hebreus 11.8-12","Pela fé Abraão obedeceu"),
    (46,3,"Seg",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Hebreus 11.17-19","Pela fé Abraão ofereceu Isaque"),
    (46,4,"Ter",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Hebreus 11.23-27","Pela fé Moisés recusou ser filho da filha de Faraó"),
    (46,5,"Qua",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Hebreus 11.32-38","Pela fé venceram reinos, obtiveram promessas"),
    (46,6,"Qui",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Marcos 9.21-24","'Eu creio! Ajuda-me na minha falta de fé!'"),
    (46,7,"Sex",12,"Guerra Espiritual e Vida de Fé","A Fé como Escudo","Romanos 4.18-22","Se fortaleceu na fé, dando glória a Deus"),
    # MÊS 13 — A Esperança Eterna e a Glória Vindoura (Sem 47-52)
    (47,1,"Sáb",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","1 Tessalonicenses 4.13-18","O Senhor descerá dos céus — consolai-vos"),
    (47,2,"Dom",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","Mateus 24.29-31","O Filho do Homem vindo sobre as nuvens"),
    (47,3,"Seg",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","Atos 1.9-11","Esse Jesus virá do modo como O vistes subir"),
    (47,4,"Ter",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","Tito 2.11-14","Aguardando a bendita esperança"),
    (47,5,"Qua",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","2 Pedro 3.8-10","O dia do Senhor virá como ladrão"),
    (47,6,"Qui",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","Apocalipse 22.12-14","'Eis que venho sem demora!'"),
    (47,7,"Sex",13,"A Esperança Eterna e a Glória Vindoura","A Volta de Cristo","Filipenses 3.20-21","A nossa pátria está nos céus"),
    (48,1,"Sáb",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","1 Coríntios 15.20-23","Cristo, as primícias"),
    (48,2,"Dom",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","1 Coríntios 15.42-49","Semeia-se natural, ressuscita espiritual"),
    (48,3,"Seg",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","Daniel 12.1-3","Uns para a vida, outros para desprezo eterno"),
    (48,4,"Ter",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","João 5.25-29","Todos os que estão nos sepulcros ouvirão"),
    (48,5,"Qua",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","Romanos 8.22-25","Aguardando a redenção do corpo"),
    (48,6,"Qui",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","2 Coríntios 5.1-5","Temos edifício eterno nos céus"),
    (48,7,"Sex",13,"A Esperança Eterna e a Glória Vindoura","A Ressurreição dos Mortos","Jó 19.25-27","Eu sei que o meu Redentor vive"),
    (49,1,"Sáb",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","Mateus 25.31-34","Separará as ovelhas dos cabritos"),
    (49,2,"Dom",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","Apocalipse 20.11-15","O grande trono branco"),
    (49,3,"Seg",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","2 Coríntios 5.10-11","O tribunal de Cristo"),
    (49,4,"Ter",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","Romanos 14.10-12","Cada um dará contas de si mesmo a Deus"),
    (49,5,"Qua",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","Eclesiastes 12.13-14","Deus há de trazer a juízo toda obra"),
    (49,6,"Qui",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","Atos 17.30-31","Deus designou um dia para julgar o mundo"),
    (49,7,"Sex",13,"A Esperança Eterna e a Glória Vindoura","O Juízo Final","Mateus 7.21-23","'Nunca vos conheci'"),
    (50,1,"Sáb",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","Apocalipse 21.1-5","'Eis que faço novas todas as coisas'"),
    (50,2,"Dom",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","Isaías 65.17-19","Crio novos céus e nova terra — alegria"),
    (50,3,"Seg",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","2 Pedro 3.11-14","Novos céus nos quais habita a justiça"),
    (50,4,"Ter",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","Apocalipse 21.22-27","O Senhor e o Cordeiro são o templo"),
    (50,5,"Qua",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","Apocalipse 22.1-5","O rio da água da vida — verão a Sua face"),
    (50,6,"Qui",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","Isaías 11.6-9","A terra se encherá do conhecimento do Senhor"),
    (50,7,"Sex",13,"A Esperança Eterna e a Glória Vindoura","Novos Céus e Nova Terra","Romanos 8.18-21","Os sofrimentos não são dignos de comparação com a glória"),
    (51,1,"Sáb",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","Deuteronômio 7.9","O Senhor é Deus fiel"),
    (51,2,"Dom",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","Salmo 36.5-9","A tua fidelidade chega até às nuvens"),
    (51,3,"Seg",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","1 Coríntios 1.4-9","Fiel é Deus, pelo qual fostes chamados"),
    (51,4,"Ter",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","2 Tessalonicenses 3.3-5","Fiel é o Senhor que vos confirmará"),
    (51,5,"Qua",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","1 Tessalonicenses 5.23-24","Fiel é o que vos chama"),
    (51,6,"Qui",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","Números 23.19","Deus não é homem para que minta"),
    (51,7,"Sex",13,"A Esperança Eterna e a Glória Vindoura","O Deus que É Fiel","Salmo 89.1-4","Cantarei para sempre as misericórdias"),
    (52,1,"Sáb",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","Romanos 11.33-36","Ó profundidade! Porque dEle são todas as coisas"),
    (52,2,"Dom",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","Apocalipse 7.9-12","A multidão incontável — louvor eterno"),
    (52,3,"Seg",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","Salmo 150.1-6","Tudo quanto tem fôlego louve ao Senhor!"),
    (52,4,"Ter",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","Efésios 3.20-21","Infinitamente mais — a Ele a glória"),
    (52,5,"Qua",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","Judas 24-25","Ao único Deus — glória, majestade, império"),
    (52,6,"Qui",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","1 Timóteo 1.17","Ao Rei eterno, imortal, invisível — honra e glória"),
    (52,7,"Sex",13,"A Esperança Eterna e a Glória Vindoura","Somente a Deus a Glória: O Grande Finale","Apocalipse 22.20-21","'Amém! Vem, Senhor Jesus!'"),
]
